disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Wiebe Vandendriessche"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/profile/profile-cropped.jpg"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "&copy; 2026 Wiebe Vandendriessche. All Rights Reserved."

[params.author]
  name = "Wiebe Vandendriessche"
  email = "wiebe.vandendriessche@ugent.be"
  image = "img/profile/profile-cropped.jpg"
  imageQuality = 96
  headline = "PhD Researcher @Ghent University, imec"
  bio = "Driving transparency, accountability, and trust across the AI supply chain, from data to deployed models."
  links = [
    { email = "mailto:wiebe.vandendriessche@ugent.be" },
    { github = "https://github.com/wiebe-vandendriessche" },
    { instagram = "https://instagram.com/wiebevandendriessche" },
    { linkedin = "https://linkedin.com/in/wiebe-vandendriessche" },
    { orcid = "https://orcid.org/0009-0001-6499-0205" },
    { researchgate = "https://www.researchgate.net/profile/Wiebe-Vandendriessche" },
  ]