# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About me"
  pageRef = "/me"
  weight = 1

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 2

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 3

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 4

[[main]]
  name = "Other"
  pageRef = "other"
  weight = 5

[[main]]
  parent = "Other"
  name = "Education"
  pageRef = "other/education"
  weight = 6

[[main]]
  parent = "Other"
  name = "Skills"
  pageRef = "other/skills"
  weight = 7

[[main]]
  parent = "Other"
  name = "Hobbies"
  pageRef = "other/hobbies"
  weight = 8

[[main]]
  parent = "Other"
  name = "cv"
  url = "/files/cv.pdf"
  pre = "download"
  weight = 9


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 21

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 22

[[footer]]
  name = "Blog RSS"
  url = "/blog/index.xml"
  weight = 20
  pre = "rss"
