
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import Navbar from "@/components/Navbar";
import Waves from "@/components/ui/waves";
import { Footer } from "@/components/ui/footer";
import FooterSection from "@/components/sections/footer/default";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className="min-h-screen">
        <div className="relative flex flex-col min-h-screen w-full">
          {/* Absolutely positioned waves background that covers the full content height */}
          <div className="absolute inset-0 w-full h-full min-h-full -z-10 pointer-events-none">
            <Waves
              lineColor="black"
              backgroundColor="rgba(255, 255, 255, 0.2)"
              waveSpeedX={0.02}
              waveSpeedY={0.01}
              waveAmpX={40}
              waveAmpY={20}
              friction={0.9}
              tension={0.01}
              maxCursorMove={120}
              xGap={12}
              yGap={36}
              className="w-full h-full min-h-full"
            />
          </div>
          <header className="z-20 backdrop-blur-md">
            <Navbar />
          </header>
          <main className="flex-1 flex flex-col justify-center items-center relative z-10">
            <NextIntlClientProvider>{children}</NextIntlClientProvider>
          </main>
          <div className="z-20 backdrop-blur-md">
            <FooterSection
              bottomOnly
              copyright="© 2025 Wiebe Vandendriessche. All rights reserved"
              policies={[
                { text: "Privacy Policy", href: "" },
                { text: "Terms of Service", href: "" },
              ]}
              showModeToggle={false}
            />
          </div>
        </div>
      </body>
    </html>
  );
}
