import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider, hasLocale, useTranslations } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import Navbar from "@/components/Navbar";
import Waves from "@/components/ui/waves";
import { Footer } from "@/components/ui/footer";
import FooterSection from "@/components/sections/footer/default";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: string } | Promise<{ locale: string }>;
}) {
  const resolvedParams = await Promise.resolve(params);
  const { locale } = resolvedParams;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  // useTranslations is a client hook, so for server layout, use a fallback or static text for Footer
  // If you need translations, fetch them server-side or pass them as props to client components
  // For now, we'll use static text for Footer
  return (
    <html lang={locale}>
      <body className="h-full">
        <div className="relative w-full" style={{ minHeight: '100vh' }}>
          {/* Absolutely positioned waves background that covers the full content height */}
          <div className="absolute inset-0 w-full" style={{ height: '100%', minHeight: '100%' }}>
            <Waves
              lineColor="black"
              backgroundColor="rgba(255, 255, 255, 0.2)"
              waveSpeedX={0.02}
              waveSpeedY={0.01}
              waveAmpX={40}
              waveAmpY={20}
              friction={0.9}
              tension={0.01}
              maxCursorMove={120}
              xGap={12}
              yGap={36}
              className="w-full h-full"
            />
          </div>
          <div className="relative flex flex-col w-full" style={{ minHeight: '100vh' }}>
            <NextIntlClientProvider locale={locale}>
              <header className="z-50 backdrop-blur-md fixed top-0 left-0 w-full">
                <Navbar />
              </header>
              <main className="flex-1 flex flex-col justify-center items-center relative z-10 pt-[64px]">
                {children}
              </main>
              <div className="z-20 backdrop-blur-md">
                <FooterSection
                  bottomOnly
                  copyright={"© 2024 Your Company"}
                  policies={[
                    { text: "Privacy", href: "" },
                    { text: "Terms", href: "" },
                  ]}
                  showModeToggle={false}
                />
              </div>
            </NextIntlClientProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
